version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: cards_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cards
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: golang:1.25
    container_name: cards_api
    working_dir: /app
    volumes:
      - .:/app
    command: go run cmd/api/main.go
    ports:
      - "8000:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

volumes:
  postgres_data:
